language: rust
cache: cargo
env:
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy-preview
script:
  - cargo test --verbose --features "fail-on-warnings"
  - cargo check --features "debug-images"
  - cargo check --features "multithreaded"
  - cargo clippy
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email: false